"""

Revision ID: 51b8a8b27e18
Revises: d37bc4322900
Create Date: 2025-09-25 00:17:20.643802

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.engine.reflection import Inspector
from aiexec.utils import migration


# revision identifiers, used by Alembic.
revision: str = '51b8a8b27e18'
down_revision: Union[str, None] = 'd37bc4322900'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    conn = op.get_bind()
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    conn = op.get_bind()
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
